version: 2
updates:

  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      # Check for updates to GitHub Actions every weekday
      interval: "daily"
      assignees:
        - "anfvelandiaer"
        - "sergiohortua"
      commit-message:
        prefix: "[PRUEBA] "
      labels:
        - "npm"
        - "PRUEBA"
      open-pull-requests-limit: 5